// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BindProject(arg1) {
  return window['go']['wailsapp']['App']['BindProject'](arg1);
}

export function CreateContext(arg1) {
  return window['go']['wailsapp']['App']['CreateContext'](arg1);
}

export function GetHomeDashboard(arg1) {
  return window['go']['wailsapp']['App']['GetHomeDashboard'](arg1);
}

export function GetLaunchState(arg1) {
  return window['go']['wailsapp']['App']['GetLaunchState'](arg1);
}

export function LaunchProject(arg1) {
  return window['go']['wailsapp']['App']['LaunchProject'](arg1);
}

export function PreflightLaunchProject(arg1) {
  return window['go']['wailsapp']['App']['PreflightLaunchProject'](arg1);
}

export function UnbindProject(arg1) {
  return window['go']['wailsapp']['App']['UnbindProject'](arg1);
}
