// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveContext(arg1) {
  return window['go']['wailsapp']['App']['ArchiveContext'](arg1);
}

export function BindProject(arg1) {
  return window['go']['wailsapp']['App']['BindProject'](arg1);
}

export function ChooseProjectDirectory() {
  return window['go']['wailsapp']['App']['ChooseProjectDirectory']();
}

export function CreateContext(arg1) {
  return window['go']['wailsapp']['App']['CreateContext'](arg1);
}

export function DeleteContext(arg1) {
  return window['go']['wailsapp']['App']['DeleteContext'](arg1);
}

export function DuplicateContext(arg1) {
  return window['go']['wailsapp']['App']['DuplicateContext'](arg1);
}

export function ExportContextMetadata(arg1) {
  return window['go']['wailsapp']['App']['ExportContextMetadata'](arg1);
}

export function GetApplicationMode() {
  return window['go']['wailsapp']['App']['GetApplicationMode']();
}

export function GetContextDetails(arg1) {
  return window['go']['wailsapp']['App']['GetContextDetails'](arg1);
}

export function GetContextTemplates() {
  return window['go']['wailsapp']['App']['GetContextTemplates']();
}

export function GetContexts() {
  return window['go']['wailsapp']['App']['GetContexts']();
}

export function GetDiagnostics(arg1) {
  return window['go']['wailsapp']['App']['GetDiagnostics'](arg1);
}

export function GetHistory() {
  return window['go']['wailsapp']['App']['GetHistory']();
}

export function GetHomeDashboard(arg1) {
  return window['go']['wailsapp']['App']['GetHomeDashboard'](arg1);
}

export function GetLaunchState(arg1) {
  return window['go']['wailsapp']['App']['GetLaunchState'](arg1);
}

export function GetProjects() {
  return window['go']['wailsapp']['App']['GetProjects']();
}

export function GetRecentProjects() {
  return window['go']['wailsapp']['App']['GetRecentProjects']();
}

export function GetRepairActions(arg1) {
  return window['go']['wailsapp']['App']['GetRepairActions'](arg1);
}

export function GetRunningEnvironments() {
  return window['go']['wailsapp']['App']['GetRunningEnvironments']();
}

export function GetSettings() {
  return window['go']['wailsapp']['App']['GetSettings']();
}

export function GetTrayState() {
  return window['go']['wailsapp']['App']['GetTrayState']();
}

export function GetTrustCenter() {
  return window['go']['wailsapp']['App']['GetTrustCenter']();
}

export function ImportContextMetadata(arg1) {
  return window['go']['wailsapp']['App']['ImportContextMetadata'](arg1);
}

export function LaunchProject(arg1) {
  return window['go']['wailsapp']['App']['LaunchProject'](arg1);
}

export function PreflightLaunchProject(arg1) {
  return window['go']['wailsapp']['App']['PreflightLaunchProject'](arg1);
}

export function PreviewDeleteContext(arg1) {
  return window['go']['wailsapp']['App']['PreviewDeleteContext'](arg1);
}

export function RestoreContext(arg1) {
  return window['go']['wailsapp']['App']['RestoreContext'](arg1);
}

export function RunRepairAction(arg1) {
  return window['go']['wailsapp']['App']['RunRepairAction'](arg1);
}

export function UnbindProject(arg1) {
  return window['go']['wailsapp']['App']['UnbindProject'](arg1);
}

export function UpdateContextAppearance(arg1) {
  return window['go']['wailsapp']['App']['UpdateContextAppearance'](arg1);
}

export function UpdateContextDetails(arg1) {
  return window['go']['wailsapp']['App']['UpdateContextDetails'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['wailsapp']['App']['UpdateSettings'](arg1);
}

export function ValidateProjectDirectory(arg1) {
  return window['go']['wailsapp']['App']['ValidateProjectDirectory'](arg1);
}
