// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';

export function BindProject(arg1:application.BindProjectRequest):Promise<any>;

export function CreateContext(arg1:application.CreateContextRequest):Promise<any>;

export function GetContextDetails(arg1:application.GetContextDetailsRequest):Promise<any>;

export function GetContexts():Promise<any>;

export function GetDiagnostics(arg1:application.GetDiagnosticsRequest):Promise<any>;

export function GetHomeDashboard(arg1:application.GetHomeDashboardRequest):Promise<any>;

export function GetLaunchState(arg1:application.GetLaunchStateRequest):Promise<any>;

export function GetProjects():Promise<any>;

export function GetRecentProjects():Promise<any>;

export function LaunchProject(arg1:application.LaunchProjectRequest):Promise<any>;

export function PreflightLaunchProject(arg1:application.PreflightLaunchProjectRequest):Promise<any>;

export function UnbindProject(arg1:application.UnbindProjectRequest):Promise<any>;
